# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: YNUOSA
subtitle: Yunnan University Open Source Association
description: Yunnan University Open Source Association
author: YNUOSA
language: en
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://ynuosa.org
root: /
permalink: :category/:year/:month/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: ynuosa-theme-random

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

#############################################
# THEME CONFIGURATION - ynuosa-theme-random #
#############################################
# html lang
language: en

# main menu navigation
menu:
  Home: index.html
  Archives: archives
  Tags: tags
  Categories: categories
  About: about
  Mirrors: http://mirrors.ynuosa.org/index/
  GitLab: https://gitlab.ynuosa.org/
  Wiki: https://wiki.ynuosa.org/

social:
  GitHub: https://github.com/YNUOSA
  # Coding.NET: https://coding.net/u/Stiekel
  # Twitter: https://twitter.com/SidCN
  # Weibo: http://weibo.com/sidcn
  # DouBan: http://www.douban.com/people/Stiekel/

# Tencent analytics
tencent_analytics: 65056164
# Google analytics
google_analytics: UA-96985531-1
# Baidu tongji
baidu_analytics:
# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname:
# Uyan
uyan_id:
# jiaThis id
# if you want to change the style of jiaThis, please go to chage the following file:
# theme/random/layouts/includes/jiathis.swig
jiaThis_uid:
jiathisConfig:
  data_track_clickback: true
  summary: ""
  showClose: true
  shortUrl: false
  hideMore: false



# Miscelaneous
favicon:

# stylesheets loaded in the <head>
stylesheets:
- /css/random.css
- /css/vegas.min.css
- /css/highlight-railscasts.css
- /css/jquery.fancybox.css
- /css/iconfont/iconfont.css
- /css/jquery.fancybox-thumbs.css
- /css/plyr.css

# scripts loaded in the end of the body
scripts:
- /js/jquery-2.2.3.min.js
- /js/vegas.min.js
- /js/random.js
- /js/highlight.pack.js
- /js/jquery.mousewheel.pack.js
- /js/jquery.fancybox.pack.js
- /js/jquery.fancybox-thumbs.js
- /js/plyr.js

# ignore visitor statistics on special server, for example on you local computer or debugging server
isIgnoreSpecialHostVisitor: true
ignoreHostList:
  - localhost
  - 127.0.0.1

# if you want to turn off the background images, pleaase set this value as true
turnoffBackgroundImage:
  # home page
  index: false
  # arcihve / categories / tags
  post_list: false
  # post and page
  post: true

# when you turn off backgrounds, you can set a background color.
backgroundColor: FDD835

backgroundImages:
- https://ooo.0o0.ooo/2017/04/17/58f47c62ebadb.jpg
- https://ooo.0o0.ooo/2017/04/17/58f47c6312c95.jpg
- https://ooo.0o0.ooo/2017/04/17/58f47c63208f3.jpg
- https://ooo.0o0.ooo/2017/04/17/58f47c6326a68.jpg

vegasConfig:
  # more about config http://vegas.jaysalvat.com/documentation/settings/
  # animation: 'random'
  # transition: 'swirlRight'
  preload­Image: true
  transition:
    - slideLeft2
    - slideRight2
    # - zoomIn
    # - swirLeft
    # - swirRight
    # - flash
    - flash2
  timer: true
  delay: 5000
  shuffle: true
  count: 28

unsplashConfig:
  # more about config on https://unsplash.it/
  # blur: true
  gravity: 'north' # north, east, south, west, center
  # greyscale: true

avatar: https://ooo.0o0.ooo/2017/04/17/58f47d5c0f1cc.png

# do not like fancybox, set this as false, this will turn it off
fancybox: true

# set the visibility of hide button in left bottom.
hideButtonVisibility: false

